global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ml-marketing-agent'
    metrics_path: /metrics
    static_configs:
      - targets: ['ml-marketing-agent:8001']
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
